-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-05-02 22:59:08 SGT
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c

SET ECHO ON
SPOOL pat_schema_output.txt

--Group number : G011
-- Group members: Gan Ming Feng
--                Tan Dae Sern
--                Ashi Dhandia

DROP TABLE driver CASCADE CONSTRAINTS;

DROP TABLE feature CASCADE CONSTRAINTS;

DROP TABLE language CASCADE CONSTRAINTS;

DROP TABLE location CASCADE CONSTRAINTS;

DROP TABLE manufacturer CASCADE CONSTRAINTS;

DROP TABLE noc CASCADE CONSTRAINTS;

DROP TABLE official CASCADE CONSTRAINTS;

DROP TABLE tcompleted CASCADE CONSTRAINTS;

DROP TABLE training CASCADE CONSTRAINTS;

DROP TABLE trip CASCADE CONSTRAINTS;

DROP TABLE vehicle CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE driver (
    d_id                   NUMBER(7) NOT NULL,
    d_fname                VARCHAR2(50),
    d_lname                VARCHAR2(50),
    d_licensenum           NUMBER(18) NOT NULL,
    d_dateofbirth          DATE NOT NULL,
    d_securitylvl          VARCHAR2(10) NOT NULL,
    d_suspended            CHAR(15) NOT NULL,
    d_totalcompletedmodule NUMBER(2) NOT NULL
);

COMMENT ON COLUMN driver.d_id IS
    'driver''s identification number';

COMMENT ON COLUMN driver.d_fname IS
    'driver''s first name';

COMMENT ON COLUMN driver.d_lname IS
    'driver last name';

COMMENT ON COLUMN driver.d_licensenum IS
    'the license number of the driver';

COMMENT ON COLUMN driver.d_dateofbirth IS
    'Driver date of birth';

COMMENT ON COLUMN driver.d_securitylvl IS
    'the security level of the driver';

COMMENT ON COLUMN driver.d_suspended IS
    'driver is suspended or not';

COMMENT ON COLUMN driver.d_totalcompletedmodule IS
    'the total number of completed module from a driver';

ALTER TABLE driver ADD CONSTRAINT driver_pk PRIMARY KEY ( d_id );

CREATE TABLE feature (
    v_id       CHAR(17) NOT NULL,
    f_features VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN feature.v_id IS
    'Vehicle ID Number';

COMMENT ON COLUMN feature.f_features IS
    'Vehicle feature';

ALTER TABLE feature ADD CONSTRAINT feature_pk PRIMARY KEY ( v_id );

CREATE TABLE language (
    l_code VARCHAR2(2) NOT NULL,
    l_name VARCHAR2(30),
    d_id   NUMBER(7) NOT NULL
);

COMMENT ON COLUMN language.l_code IS
    'code of the language spoken';

COMMENT ON COLUMN language.l_name IS
    'Name of the language spoken';

COMMENT ON COLUMN language.d_id IS
    'driver''s identification number';

ALTER TABLE language ADD CONSTRAINT language_pk PRIMARY KEY ( l_code );

CREATE TABLE location (
    loc_id           NUMBER(4) NOT NULL,
    loc_name         VARCHAR2(50),
    loc_type         VARCHAR2(50),
    loc_streetnumber NUMBER(3),
    loc_streetname   VARCHAR2(50),
    loc_postalcode   NUMBER(8),
    loc_city         VARCHAR2(50)
);

COMMENT ON COLUMN location.loc_id IS
    'location identification number';

COMMENT ON COLUMN location.loc_name IS
    'name of location';

COMMENT ON COLUMN location.loc_type IS
    'type of location';

COMMENT ON COLUMN location.loc_streetnumber IS
    'location street number ';

COMMENT ON COLUMN location.loc_streetname IS
    'Location street name';

COMMENT ON COLUMN location.loc_postalcode IS
    'location post code';

COMMENT ON COLUMN location.loc_city IS
    'Location city';

ALTER TABLE location ADD CONSTRAINT location_pk PRIMARY KEY ( loc_id );

CREATE TABLE manufacturer (
    m_vehiclemodel VARCHAR2(50) NOT NULL,
    m_vehiclemake  VARCHAR2(30) NOT NULL
);

COMMENT ON COLUMN manufacturer.m_vehiclemodel IS
    'Vehicle model';

COMMENT ON COLUMN manufacturer.m_vehiclemake IS
    'Vehicle Make';

ALTER TABLE manufacturer ADD CONSTRAINT manufacturer_pk PRIMARY KEY ( m_vehiclemodel );

CREATE TABLE noc (
    n_ioccode     VARCHAR2(20) NOT NULL,
    n_countryname CHAR(30),
    n_population  NUMBER(11),
    o_id          VARCHAR2(7) NOT NULL
);

COMMENT ON COLUMN noc.n_ioccode IS
    'National Olympic Committee''s IOC code';

COMMENT ON COLUMN noc.n_countryname IS
    'National Olympic Committee''s Country Name';

COMMENT ON COLUMN noc.n_population IS
    'National Olympic Committee''s population';

COMMENT ON COLUMN noc.o_id IS
    'official''s identification number';

CREATE UNIQUE INDEX noc__idx ON
    noc (
        o_id
    ASC );

ALTER TABLE noc ADD CONSTRAINT noc_pk PRIMARY KEY ( n_ioccode );

CREATE TABLE official (
    o_id      VARCHAR2(7) NOT NULL,
    o_fname   VARCHAR2(50),
    o_lname   VARCHAR2(50),
    o_role    VARCHAR2(30) NOT NULL,
    n_ioccode VARCHAR2(20) NOT NULL
);

COMMENT ON COLUMN official.o_id IS
    'official''s identification number';

COMMENT ON COLUMN official.o_fname IS
    'official''s first name';

COMMENT ON COLUMN official.o_lname IS
    'official''s last name';

COMMENT ON COLUMN official.o_role IS
    'official with an administrator role';

COMMENT ON COLUMN official.n_ioccode IS
    'National Olympic Committee''s IOC code';

ALTER TABLE official ADD CONSTRAINT official_pk PRIMARY KEY ( o_id );

CREATE TABLE tcompleted (
    tc_no            NUMBER(4) NOT NULL,
    d_id             NUMBER(7) NOT NULL,
    tm_code          VARCHAR2(20) NOT NULL,
    tc_datecompleted DATE NOT NULL
);

COMMENT ON COLUMN tcompleted.tc_no IS
    'trainingcompleted number (Surrogate PK)';

COMMENT ON COLUMN tcompleted.d_id IS
    'driver''s identification number';

COMMENT ON COLUMN tcompleted.tm_code IS
    'the code of the training module';

COMMENT ON COLUMN tcompleted.tc_datecompleted IS
    'the completed date of the training module that was completed';

ALTER TABLE tcompleted ADD CONSTRAINT tcompleted_pk PRIMARY KEY ( tc_no );

ALTER TABLE tcompleted ADD CONSTRAINT tcompleted_d_id_tm_code_un UNIQUE ( d_id,
                                                                          tm_code );

CREATE TABLE training (
    tm_code         VARCHAR2(20) NOT NULL,
    tm_name         VARCHAR2(50),
    tm_desc         VARCHAR2(50),
    tm_expiryperiod DATE NOT NULL,
    tm_length       NUMBER(1) NOT NULL
);

ALTER TABLE training
    ADD CONSTRAINT chk_module_length CHECK ( tm_length BETWEEN 1 AND 5 );

COMMENT ON COLUMN training.tm_code IS
    'the code of the training module';

COMMENT ON COLUMN training.tm_name IS
    'name of the training module';

COMMENT ON COLUMN training.tm_desc IS
    'description of the training module';

COMMENT ON COLUMN training.tm_expiryperiod IS
    'the expiry period for the training module';

COMMENT ON COLUMN training.tm_length IS
    'Training module length';

ALTER TABLE training ADD CONSTRAINT training_pk PRIMARY KEY ( tm_code );

CREATE TABLE trip (
    t_no                    NUMBER(4) NOT NULL,
    t_id                    NUMBER(4) NOT NULL,
    t_passengernum          NUMBER(2) NOT NULL,
    t_intended_pickup_time  DATE NOT NULL,
    t_actual_pickup_time    DATE NOT NULL,
    t_intended_dropoff_time DATE NOT NULL,
    t_actual_dropoff_time   DATE NOT NULL,
    o_id                    VARCHAR2(7) NOT NULL,
    d_id                    NUMBER(7) NOT NULL,
    v_id                    CHAR(17) NOT NULL,
    loc_id                  NUMBER(4) NOT NULL
);

COMMENT ON COLUMN trip.t_no IS
    'Trip number (Surrogate PK)';

COMMENT ON COLUMN trip.t_id IS
    'Trip id';

COMMENT ON COLUMN trip.t_passengernum IS
    'Trip Passenger number';

COMMENT ON COLUMN trip.t_intended_pickup_time IS
    'Intended pickup time for the trip';

COMMENT ON COLUMN trip.t_actual_pickup_time IS
    'Actual pick up time for the trip';

COMMENT ON COLUMN trip.t_intended_dropoff_time IS
    'Intended drop off time for the trip';

COMMENT ON COLUMN trip.t_actual_dropoff_time IS
    'Actual drop off time for the trip';

COMMENT ON COLUMN trip.o_id IS
    'official''s identification number';

COMMENT ON COLUMN trip.d_id IS
    'driver''s identification number';

COMMENT ON COLUMN trip.v_id IS
    'Vehicle ID Number';

COMMENT ON COLUMN trip.loc_id IS
    'location identification number';

ALTER TABLE trip ADD CONSTRAINT trip_pk PRIMARY KEY ( t_no );

ALTER TABLE trip
    ADD CONSTRAINT trip_t_id_o_id_d_id_v_id_un UNIQUE ( t_id,
                                                        o_id,
                                                        d_id,
                                                        v_id );

CREATE TABLE vehicle (
    v_id                CHAR(17) NOT NULL,
    v_registrationplate CHAR(7) NOT NULL,
    v_manufacture_year  DATE NOT NULL,
    v_odometerreading   NUMBER(7) NOT NULL,
    v_nopassengers      NUMBER(2) NOT NULL,
    d_id                NUMBER(7) NOT NULL,
    m_vehiclemodel      VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN vehicle.v_id IS
    'Vehicle ID Number';

COMMENT ON COLUMN vehicle.v_registrationplate IS
    'Vehicle registration number';

COMMENT ON COLUMN vehicle.v_manufacture_year IS
    'Vehicle manufacturer year';

COMMENT ON COLUMN vehicle.v_odometerreading IS
    'Vehicle current odometer';

COMMENT ON COLUMN vehicle.v_nopassengers IS
    'Number of passengers
';

COMMENT ON COLUMN vehicle.d_id IS
    'driver''s identification number';

COMMENT ON COLUMN vehicle.m_vehiclemodel IS
    'Vehicle model';

ALTER TABLE vehicle ADD CONSTRAINT vehicle_pk PRIMARY KEY ( v_id );

ALTER TABLE feature
    ADD CONSTRAINT feature_vehicle_fk FOREIGN KEY ( v_id )
        REFERENCES vehicle ( v_id );

ALTER TABLE language
    ADD CONSTRAINT language_driver_fk FOREIGN KEY ( d_id )
        REFERENCES driver ( d_id );

ALTER TABLE noc
    ADD CONSTRAINT noc_official_fk FOREIGN KEY ( o_id )
        REFERENCES official ( o_id );

ALTER TABLE official
    ADD CONSTRAINT official_noc_fk FOREIGN KEY ( n_ioccode )
        REFERENCES noc ( n_ioccode );

ALTER TABLE tcompleted
    ADD CONSTRAINT tcompleted_driver_fk FOREIGN KEY ( d_id )
        REFERENCES driver ( d_id );

ALTER TABLE tcompleted
    ADD CONSTRAINT tcompleted_training_fk FOREIGN KEY ( tm_code )
        REFERENCES training ( tm_code );

ALTER TABLE trip
    ADD CONSTRAINT trip_driver_fk FOREIGN KEY ( d_id )
        REFERENCES driver ( d_id );

ALTER TABLE trip
    ADD CONSTRAINT trip_location_fk FOREIGN KEY ( loc_id )
        REFERENCES location ( loc_id );

ALTER TABLE trip
    ADD CONSTRAINT trip_official_fk FOREIGN KEY ( o_id )
        REFERENCES official ( o_id );

ALTER TABLE trip
    ADD CONSTRAINT trip_vehicle_fk FOREIGN KEY ( v_id )
        REFERENCES vehicle ( v_id );

ALTER TABLE vehicle
    ADD CONSTRAINT vehicle_driver_fk FOREIGN KEY ( d_id )
        REFERENCES driver ( d_id );

ALTER TABLE vehicle
    ADD CONSTRAINT vehicle_manufacturer_fk FOREIGN KEY ( m_vehiclemodel )
        REFERENCES manufacturer ( m_vehiclemodel );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            11
-- CREATE INDEX                             1
-- ALTER TABLE                             26
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0

SPOOL off
set echo off